package cloud.autotests.utilities;

import cloud.autotests.api.project.CreateProjectRequestDto;
import com.github.javafaker.Faker;

public class ProjectGenerator {

    public static CreateProjectRequestDto generateProject(boolean projectVisibility) {
        return CreateProjectRequestDto.builder()
                .name("autogenerated-project-" + new Faker().random().hex(6))
                .isPublic(projectVisibility)
                .build();
    }
}
